Use DEM-stitcher
dbekaert/RAiDER pull request #318
Opened 2021-08-12 18:22 UTC by cmarshak

## Description
See: https://github.com/dbekaert/RAiDER/issues/293

1. Use [GLO-30 DEM](https://registry.opendata.aws/copernicus-dem/) from open s3 bucket.
2. Ensure that DEM is in area centered-coordinates. Note that GLO-30 is distributed with "pixel as point" (see this [discussion](https://github.com/OSGeo/gdal/issues/1505#issuecomment-489469904)) - can verify inspecting original tile gdal tags.

## Motivation and Context
Make sure that DEM is in area coordinates.

## How Has This Been Tested?

This is imported from a different library that is distributed on pypi with tests.

```
# Bay area
bounds = [-121.5, 34.95, -120.2, 36.25]
extent = [bounds[1], bounds[3], bounds[0], bounds[2]]
from RAiDER.dem import getDEM
getDEM(extent)
```

The resulting data is called `glo_30.dem.wgs84` in the current working directory.

See above.

N/A

N/A

## Screenshots (if appropriate):

## Type of change

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ x ] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [ ] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-08-12 18:25 UTC, cmarshak commented
I will not do virtual warping because other DEMs are not in gdal readable format on the servers they are stored e.g. 3dep. This would require more work and logic. Moreover, tiles are removed after downloaded. Very useful to have feature to download original tiles (and save if necessary) for debugging/inspecting resampling.

2021-08-12 20:02 UTC, cmarshak commented
As an FYI, the builds are taking 20 minutes now. That's a really long time. One of the builds exited with code [137](https://support.circleci.com/hc/en-us/articles/115014359648-Exit-code-137-Out-of-memory#:~:text=This%20is%20a%20Linux%20error,memory%2C%20your%20build%20will%20fail.) - and thats before pytest was run. I tested things locally fine.

```...
============================ 253 passed, 5 skipped, 64813 warnings in 60.00s (0:01:00) ============================
```

This build issue maybe an issue I will have to address another time.

2021-08-16 20:29 UTC, jlmaurer requested changes
Looks like there is a typo in the arguments, otherwise looks good! 

A question on this: is the DEM that ends up getting downloaded already ellipsoidal-corrected? If so we should probably wait to merge until we can apply the same correction to the weather model grid node elevations.

2021-08-16 20:29 UTC, jlmaurer commented on tools/RAiDER/dem.py
> +    extent : list
Should include the ordering of the bounding box elements

2021-08-16 20:29 UTC, jlmaurer commented on tools/RAiDER/dem.py
> +        A list containing [lat_min, lat_max, lon_min, lon_max]
Looks like this line should up a line?

2021-08-16 20:29 UTC, jlmaurer commented on tools/RAiDER/dem.py
> +    extent : list
Saw the list below, just seems to be in the wrong place?

2021-08-18 17:43 UTC, cmarshak commented
Yea - I flipped the descriptions in the docstring.

I updated that and removed some functions that were no longer being used.

2021-08-18 17:46 UTC, cmarshak commented
> question on this: is the DEM that ends up getting downloaded already ellipsoidal-corrected? If so we should probably wait to merge until we can apply the same correction to the weather model grid node elevations.

Not quiet. Each DEM is referenced to a geoid. GLO-30 is EGM-08 and SRTMv3 is EGM-96. In this update, we convert these heights into the ellipsoidal heights.  We can convert to specific geoid as well depending on what is needed. We should coordinate more about what is needed for RAiDER.

2021-08-31 15:13 UTC, jlmaurer commented
@cmarshak looks good to me.

2021-08-31 15:14 UTC, jlmaurer approved these changes

2021-08-31 15:14 UTC, merged