Avoid duplicate datetime keys
dbekaert/RAiDER pull request #573
Opened 2023-08-04 21:57 UTC by sssangha

## Description
Fix bug where `Datetime` column is duplicated in file of GNSS delays, which leads to an error when attempting to subset the dataframe WRT to the CSV containing WM delays.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-08-04 21:59 UTC, bbuzz31 approved these changes

2023-08-05 00:00 UTC, bbuzz31 requested changes
This produces same error as previously because the other datetime column is a string not datetime

2023-08-06 01:00 UTC, jlmaurer approved these changes
LGTM

2023-08-15 20:18 UTC, bbuzz31 approved these changes

2023-08-16 01:23 UTC, bbuzz31 commented
@sssangha this should be merged, is there a reason you closed it without doing so?

2023-08-18 00:06 UTC, merged